#!/bin/bash
#
# Asserts that every output a user sees carries the plugin's attribution line,
# naming the skill that produced it.
#
# The line is hardcoded per skill rather than pulled from a shared reference,
# because a skill would otherwise have to read another file before it could print
# its own footer. The cost of that choice is drift — a renamed skill, a rewritten
# template, or a new skill shipped without a signature — and this test is what
# pays it back. Same bargain as check-version-sync.sh: repeat the string, then
# assert the copies agree.
#
# Each rendered output needs the line twice, header and footer, so a report stays
# attributed when someone screenshots only its top or pastes only its tail. Where
# the output is HTML, the pair lives in the asset and SKILL.md carries only the
# instruction to copy it through — hence the differing counts below.

set -uo pipefail

REPO_ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO_ROOT"

PREFIX="Generated by Qase Quality Supervisor · "

failures=0
pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1" >&2; failures=$((failures + 1)); }

# $1 file, $2 signature suffix, $3 required number of lines carrying it
expect_signature() {
  local file="$1" suffix="$2" want="$3" got
  if [ ! -f "$file" ]; then
    fail "$file does not exist."
    return
  fi
  got="$(grep -cF "${PREFIX}${suffix}" "$file")"
  if [ "$got" -eq "$want" ]; then
    pass "$file carries '${PREFIX}${suffix}' on $want line(s)."
  else
    fail "$file should carry '${PREFIX}${suffix}' on $want line(s), found $got." \
      && echo "      A signature broken across two lines does not count — keep it on one." >&2
  fi
}

# Skills whose output is a markdown report printed in chat: the pair lives in the
# report template inside SKILL.md.
for skill in analyzing-test-coverage analyzing-test-flakiness \
             assessing-release-readiness triaging-test-failures; do
  expect_signature "skills/$skill/SKILL.md" "$skill skill" 2
done

# Skills whose output is an HTML file: the pair lives in the template asset, and
# SKILL.md states the requirement to carry it through.
expect_signature "skills/reporting-quality-pulse/assets/pulse-template.html" \
  "reporting-quality-pulse skill" 2
expect_signature "skills/reporting-quality-pulse/SKILL.md" \
  "reporting-quality-pulse skill" 1
expect_signature "skills/analyzing-change-impact/assets/impact-template.html" \
  "analyzing-change-impact skill" 2
# Two in SKILL.md: the carry-through requirement, and the ticket comment, which is
# the one output that leaves the machine.
expect_signature "skills/analyzing-change-impact/SKILL.md" \
  "analyzing-change-impact skill" 2

# The consolidated report signs itself at each end as the command — never as the
# four skills it folds in.
expect_signature "commands/quality-report.md" "quality-report" 2

# A new skill must not ship unsigned.
for dir in skills/*/; do
  skill="$(basename "$dir")"
  if ! grep -qF "${PREFIX}${skill} skill" "${dir}SKILL.md"; then
    fail "skills/$skill carries no attribution line — every skill signs its output."
  fi
done

# A signature naming something that is neither a skill nor the command means a
# rename missed a file.
while read -r named; do
  [ -n "$named" ] || continue
  [ "$named" = "quality-report" ] && continue
  if [ ! -d "skills/$named" ]; then
    fail "attribution names '$named', which is not a skill in skills/."
  fi
done < <(grep -rhoE "${PREFIX}[a-z][a-z-]*" --include='*.md' --include='*.html' . \
         | sed "s/.*· //" | sort -u)

if [ "$failures" -gt 0 ]; then
  echo "$failures branding check(s) failed." >&2
  exit 1
fi
echo "All branding tests passed."
